name: dicoding_media
description: Dicoding Social Media

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0
  sizer: ^1.1.8
  rxdart: ^0.24.1
  page_transition: ^1.1.6
  cached_network_image: ^2.5.1
  equatable: ^1.2.3
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  data_connection_checker: ^0.3.4
  modal_bottom_sheet: ^2.0.0
  dotted_border: ^2.0.0
  carousel_slider: ^3.0.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_typeahead: ^3.1.3
  plugin_platform_interface: ^2.0.0
  image_picker: ^0.8.0
  splashscreen: ^1.3.5
  form_validator: ^0.1.7
  permission_handler: ^8.0.1
  shared_preferences: ^2.0.6
  infinite_scroll_pagination: ^3.0.1+1
  settings_ui: ^1.0.0
  photo_view: ^0.11.1
  flutter_easyloading: ^3.0.0
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.10.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/google/google_sans_regular.ttf